image: maven:3-openjdk-8
stages:
  - verify
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
verify:
  stage: verify
  script:
    - mvn $MAVEN_OPTS clean verify
  artifacts:
    paths:
      - target/site/serenity/*